services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_REQUIRE_SSL: ${POSTGRES_REQUIRE_SSL:-false}
      POSTGRES_SSL_CERT_PATH: ${POSTGRES_SSL_CERT_PATH:-/etc/certs/postgresql.crt}
      POSTGRES_SSL_KEY_PATH: ${POSTGRES_SSL_KEY_PATH:-/etc/certs/postgresql.key}
      TZ: ${POSTGRES_TZ:-Europe/Berlin}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./certs:/etc/certs:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    ports:
      - "${POSTGRES_PORT}:5432"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.entrypoints=postgresql"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
    restart: unless-stopped

  app:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backup:
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    volumes:
      - ./backups:/app/backups
    networks:
      - app_network
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 12
      BACKUP_KEEP_YEARS: 5
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    name: ${POSTGRES_DB}_pgdata
    driver: local
